### ISSUE TITLE
Configurable listening port to run without root

### ISSUE THREAD

**Issue by qdm12** [wishthis/docker#9]
It would be nice to have the listening port configurable, so the container can be ran without root.

Ideally and even better would be to default to `8000` and run as non-root, for example with instruction

```Dockerfile
USER 1000
```

Thanks!

**Comment by Hiobi** [comment]
Hi,

Thanks for opening this issue.

- I'll be looking about configurable port. Actually it's expose via port 80 (like wishthis). You still able to mapping it with PORTS: `docker run -p 8000:80 hiob/wishthis:stable`
- Actually the container running with user www-data.

**Comment by qdm12** [comment]
Oh indeed, I missed `USER www-data` 😉 No point changing it then really, I'll close the issue, thanks!
